### ISSUE TITLE
Image Generation can't find ['bias_proposals'] in coco_train.json

### ISSUE THREAD

**Issue by JustinKai0527** [Picsart-AI-Research/OpenBias#1]
such a amazing work, I try to reproduce your work, in **bias proposals** part you give the available of coco json so I just download it, but I found that the **image generation** when trying to open coco_train.json terminal say can't find the ['bias_proposals'], the json file only have ['bias_detection'] & ['detected_biases']
![Uploading image.png…]()

**Comment by Moreno98** [comment]
Thank you for spotting this discrepancy. I have uploaded the correct files and updated the links.
