### ISSUE TITLE
COCO_train.json format wrong?

### ISSUE THREAD

**Issue by JustinKai0527** [Picsart-AI-Research/OpenBias#2]
Outstanding work!
I want to ask the file you gave coco_train & flickr_30k json file the file can't feed into the image generation due to the format wrong
![image](https://github.com/Picsart-AI-Research/OpenBias/assets/103019623/d6db3458-9bc5-4da2-a005-5ce17c790d4a)
the json format is bias_detection but the code need bias_proposal

**Comment by Moreno98** [comment]
Thank you for spotting this discrepancy. I have uploaded the correct files and updated the links.
